---
- name: Install Deluge
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "deluge-daemon"
    - "deluge-web"

- name: Template Deluge Config
  become: true
  ansible.builtin.template:
    src: "core.conf.j2"
    dest: "/var/lib/deluge/.config/deluge/core.conf"
    owner: "deluge"
    group: "deluge"
    mode: "0600"

- name: Enable and Start Deluge Service
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - "deluge-daemon"
    - "deluge-web"
