- name: Configure Server
  hosts: all
  roles:
    - upgrade
    - podman
    - firewall
    - samba
    - role: nginx
      tags: containers
    - cockpit
    - deluge
    - role: quadlet
      tags: containers
    - role: youtube
