- name: Check if Certificate Exists
  become: true
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ certbot_fqdn }}/cert.pem"
  register: certbot_letsencrypt_cert

- name: Install certbot
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "certbot"
    - "python3-certbot-dns-cloudflare"

- name: Configure Certbot Email
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/letsencrypt/cli.ini"
    line: "email = {{ certbot_email }}"

- name: Create Secrets Directory
  become: true
  ansible.builtin.file:
    path: "/etc/letsencrypt/secrets"
    state: directory
    mode: "0700"

- name: Template Cloudflare Config
  become: true
  ansible.builtin.template:
    src: "cloudflare.ini.j2"
    dest: "{{ certbot_secrets_path }}"
    mode: "0400"

- name: Generate Certificate
  become: true
  ansible.builtin.command: "{{ certbot_command }}"
  when: not certbot_letsencrypt_cert.stat.exists
  changed_when: not certbot_letsencrypt_cert.stat.exists
