title: "Dashboard"
subtitle: "Titanium-Server"
footer: ""
services:
  - items:
      - name: "Cockpit"
        icon: "fab fa-fedora"
        url: "https://cockpit.titanium-server.thelux.family"
      - name: "Notes"
        icon: "fas fa-note-sticky"
        url: "https://notes.titanium-server.thelux.family"
      - name: "RSS"
        icon: "fas fa-rss"
        url: "https://rss.titanium-server.thelux.family"
      - name: "Jellyfin"
        icon: "fas fa-play-circle"
        url: "https://jellyfin.titanium-server.thelux.family"
      - name: "Music"
        icon: "fas fa-music"
        url: "https://music.titanium-server.thelux.family"
      - name: "Roms"
        icon: "fas fa-gamepad"
        url: "https://roms.titanium-server.thelux.family"
      - name: "Radarr"
        icon: "fas fa-file-video"
        url: "https://radarr.titanium-server.thelux.family"
      - name: "Sonarr"
        icon: "fas fa-file-video"
        url: "https://sonarr.titanium-server.thelux.family"
      - name: "Prowlarr"
        icon: "fas fa-download"
        url: "https://prowlarr.titanium-server.thelux.family"
      - name: "Torrents"
        icon: "fas fa-download"
        url: "https://torrent.titanium-server.thelux.family"
